name: warframestat_client
version: 3.14.0
description: A simple client wrapper around WFCD worldstate api with included models for warframe-items.
homepage: https://github.com/WFCD
repository: https://github.com/WFCD/warframestat_client

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ">=1.17.0 <2.0.0"
  equatable: ">=2.0.7 <3.0.0"
  http: ">=1.1.0 <2.0.0"
  json_annotation: ">=4.9.0 <5.0.0"
  meta: ">=1.16.0 <2.0.0"
  web_socket_client: ">=0.1.5 <2.0.0"

dev_dependencies:
  build_runner: ^2.4.13
  commitlint_cli: ^0.8.1
  husky: ^0.1.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  path: ^1.8.3
  test: ^1.25.9
  very_good_analysis: ^6.0.0
